version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: agromind_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PORT=8000
    networks:
      - agromind_net

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agromind_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - agromind_net

networks:
  agromind_net:
    driver: bridge